const stampComponents = [
  { name: "id", type: "uint256" },
  { name: "builder", type: "address" },
  { name: "project", type: "string" },
  { name: "repository", type: "string" },
  { name: "commitSha", type: "string" },
  { name: "deploymentUrl", type: "string" },
  { name: "milestone", type: "string" },
  { name: "manifestHash", type: "bytes32" },
  { name: "proofSchemaVersion", type: "string" },
  { name: "timestamp", type: "uint64" },
] as const;

export const shipStampRegistryAbi = [
  { type: "error", name: "StampNotFound", inputs: [{ name: "stampId", type: "uint256" }] },
  { type: "error", name: "DuplicateStamp", inputs: [{ name: "duplicateKey", type: "bytes32" }] },
  { type: "error", name: "ManifestHashMismatch", inputs: [{ name: "expected", type: "bytes32" }, { name: "provided", type: "bytes32" }] },
  { type: "function", name: "totalStamps", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  {
    type: "function",
    name: "stampBuild",
    stateMutability: "nonpayable",
    inputs: [{ name: "input", type: "tuple", components: [
      { name: "project", type: "string" },
      { name: "repository", type: "string" },
      { name: "commitSha", type: "string" },
      { name: "deploymentUrl", type: "string" },
      { name: "milestone", type: "string" },
      { name: "manifestHash", type: "bytes32" },
      { name: "proofSchemaVersion", type: "string" },
    ] }],
    outputs: [{ name: "stampId", type: "uint256" }],
  },
  { type: "function", name: "getStamp", stateMutability: "view", inputs: [{ name: "stampId", type: "uint256" }], outputs: [{ name: "stamp", type: "tuple", components: stampComponents }] },
  { type: "function", name: "getProjectStampCount", stateMutability: "view", inputs: [{ name: "repository", type: "string" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "getProjectStamps", stateMutability: "view", inputs: [{ name: "repository", type: "string" }, { name: "offset", type: "uint256" }, { name: "limit", type: "uint256" }], outputs: [{ name: "stamps", type: "tuple[]", components: stampComponents }] },
  { type: "function", name: "isDuplicate", stateMutability: "view", inputs: [{ name: "builder", type: "address" }, { name: "repository", type: "string" }, { name: "commitSha", type: "string" }, { name: "deploymentUrl", type: "string" }, { name: "manifestHash", type: "bytes32" }], outputs: [{ name: "", type: "bool" }] },
  {
    type: "event",
    name: "BuildStamped",
    anonymous: false,
    inputs: [
      { name: "stampId", type: "uint256", indexed: true },
      { name: "builder", type: "address", indexed: true },
      { name: "projectKey", type: "bytes32", indexed: true },
      { name: "manifestHash", type: "bytes32", indexed: false },
      { name: "proofSchemaVersion", type: "string", indexed: false },
      { name: "timestamp", type: "uint64", indexed: false },
    ],
  },
] as const;
