[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
metadata = true
metadata_hash = "none"
use_literal_content = true

[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC_URL}"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

